name: Deploy Prod PakarGaming Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Dashboard (Prod)
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Dashboard
        shell: bash
        run: |
          set -e

          echo "Workspace: $GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"

          echo "Listing files"
          ls -la

          echo "🔨 Building new image..."
          if docker compose -f docker-compose.prod.yml build; then
            echo "✅ Build success"

            echo "🚀 Restarting container..."
            docker compose -f docker-compose.prod.yml up -d

            echo "🎉 Deploy success"
          else
            echo "❌ Build failed!"
            echo "⚠️ Keeping previous running container"
            exit 1
          fi
